version: '3.8'

services:
  backend:
    container_name: tasks_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8050:8000
    env_file:
      - ./backend/app/.env

